### ISSUE TITLE
Failed when running this plugin

### ISSUE THREAD

**Issue by chunibalon** [patois/HRDevHelper#3]
Hello, when I load this plugin through the hotkey or Edit menu, this issue occurs on both IDA7.5(Win10) and IDA7.5(MacOS). I tried to find it out but it seems to related to a config file?

**Comment by chunibalon** [comment]
The error message:
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Users/IDA/plugins/hrdevhelper.py", line 515, in run
    cg = cfunc_graph_t(focusitem, self.config, close_open=True)
  File "C:/Users/IDA/plugins/hrdevhelper.py", line 214, in __init__
    self.center_node = config["options"]["center"]
KeyError: 'options'

**Comment by patois** [comment]
Could you please try deleting the config file (create a backup if you adjusted settings), then restart IDA and rerun the plugin? You can find the config file in %APPDATA%\Roaming\Hex-Rays\IDA Pro\plugins\HrDevHelper.cfg

**Comment by chunibalon** [comment]
I have saw the %APPDATA%\Roaming\Hex-Rays\IDA Pro\plugins\HrDevHelper.cfg and I found that the %APPDATA%\Roaming\Hex-Rays\IDA Pro\plugins folder does not exist, so I create one and it works! Thanks!

**Comment by patois** [comment]
Thanks for pointing out this issue, which has been fixed with [this commit](https://github.com/patois/HRDevHelper/commit/53baec17b95ecb74b7ad50087010df6ee1e77733). Previous versions wrongly assumed that the IDA installer created a "plugins" directory underneath %APPDATA%\Roaming\Hex-Rays\IDA Pro\
